package(default_visibility = ["//visibility:public"])

cc_library(
  name = "minic_parser",
  hdrs = [
    "minic_parser.h",
  ],
  srcs = [
    "minic_parser.cc",
  ],
  deps = [
    "//dvc:parser",
    "//dvc:scanner",
  ],
)
