package(default_visibility = ["//visibility:public"])

cc_library(
    name = "minic_parser",
    srcs = [
        "minic_parser.cc",
    ],
    hdrs = [
        "minic_parser.h",
    ],
    deps = [
        "//dvc:parser",
        "//dvc:scanner",
    ],
)
