package(default_visibility = ["//visibility:public"])

cc_library(
    name = "file",
    hdrs = [
       "file.h",
    ],
)

cc_library(
    name = "scanner",
    hdrs = [
        "scanner.h",
    ],
)

cc_library(
    name = "parser",
    hdrs = [
        "parser.h",
    ],
)

cc_library(
    name = "json",
    hdrs = [
        "json.h",
    ],
)

cc_library(
    name = "container",
    hdrs = [
        "container.h",
    ],
)

cc_library(
    name = "string",
    hdrs = [
        "string.h",
    ],
)